dynamic_background_opacity yes
#enable_background_blur yes

background_opacity 0.9
#background_blur 1

window_padding_width 15
font_size 16
include current-theme.conf
# BEGIN_KITTY_THEME
# Catppuccin-Macchiato
# END_KITTY_THEME
