#!/usr/bin/env bash


# Copy and paste all config files to my system

XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
dry="0"

while [[ $# -gt 0 ]]; do
    if [[ $1 == "--dry" ]]; then
        dry="1"
    fi
    shift
done

log() {
    if [[ $dry == "1" ]]; then
        echo "[DRY_RUN]: $@"
    else
        echo "$@"
    fi
}

execute() {
	if [[ $dry == "1" ]]; then
		echo "[DRY_RUN]: $*"
	else
		echo "[EXEC]: $*"
		"$@"
	fi
}

log "--------- DEV-ENV ---------"

copy_dir() {
    from=$1
    to=$2
    execute mkdir -p "$to"

    pushd "$from" > /dev/null
    dirs=$(find . -mindepth 1 -maxdepth 1 -type d)
    for dir in $dirs; do
        execute rm -rf "$to/$dir"
        execute cp -a "$dir" "$to/$dir"
    done
    popd > /dev/null
}

copy_file() {
    from=$1
    to=$2

    execute mkdir -p "$to"
    name=$(basename $from)
    execute rm -f "$to/$name"
    execute cp -a "$from" "$to/$name"
}

copy_dir env/.config $XDG_CONFIG_HOME
copy_file env/.zshrc $HOME
copy_file env/.bashrc $HOME
copy_file env/.config/starship.toml $XDG_CONFIG_HOME
# tmux stuff
copy_file env/.tmux.conf $HOME
copy_file env/.tmux-sessionizer $HOME
# copy_file env/.ready-tmux $HOME
copy_dir .local $HOME/.local

hyprctl reload
