#!/usr/bin/env bash

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

filter=""
dry="0"

while [[ $# > 0 ]]; do
    if [[ $1 == "--dry" ]]; then
        dry="1"
    else
        filter="$1"
    fi
    shift
done

log() {
    if [[ $dry == "1" ]]; then
        echo "[DRY_RUN]: $@"
    else
        echo "$@"
    fi
}

execute() {
    log "execute $@"
    if [[ $dry == "1" ]]; then
        echo "[DRY_RUN]: $@"
    fi
    "$@"
}

log "$script_dir -- $filter"

cd "$script_dir" || exit 1

find runs -maxdepth 1 -mindepth 1 -executable -type f | while read -r script; do
    if [[ -n  "$filter" && "$script" != *"$filter"* ]]; then
        log "filtered: $filter -- $script"
        continue
    fi
    execute "./$script"
done
