#!/usr/bin/env bash

flatpak install flathub org.midori_browser.Midori

# Download the latest Google Chrome .deb package
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

# Install the package using apt (this handles dependencies automatically)
sudo apt install -y ./google-chrome-stable_current_amd64.deb

# Clean up the downloaded file
rm google-chrome-stable_current_amd64.deb
