#!/usr/bin/env bash

echo "Install neovim 🧘‍♂"

sudo apt install ninja-build gettext cmake curl build-essential git

git clone https://github.com/neovim/neovim "$HOME/neovim"

cd $HOME/neovim || exit 1
git checkout stable
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install

echo "Done installation success neovim 🧘‍♂"
