#!/usr/bin/env bash 

set -e

echo "install Bitwarden Desktop"

sudo apt install -y libsecret-1-0

echo "Recherche de la dernière version sur GitHub..."

# Récupération de l'URL du dernier fichier .deb via l'API GitHub
LATEST_URL=$(curl -s https://api.github.com/repos/bitwarden/clients/releases/latest \
| grep "browser_download_url.*Desktop-.*\.deb" \
| cut -d '"' -f 4 | head -n 1)

if [ -z "$LATEST_URL" ]; then
    echo "Erreur : Impossible de trouver l'URL de téléchargement."
    exit 1
fi

FILE_NAME="bitwarden_latest_amd64.deb"

echo "Téléchargement de : $FILE_NAME..."
wget -O "/tmp/$FILE_NAME" "$LATEST_URL"

echo "Installation du paquet..."
sudo apt install -y "/tmp/$FILE_NAME"

# Nettoyage
rm "/tmp/$FILE_NAME"
