#!/usr/bin/env bash

# ========================================
# GNOME - Environnement de bureau stable
# ========================================
# GNOME complet avec toutes ses applications
# sudo pacman -S --noconfirm --needed gnome

# Si tu veux GNOME minimal (sans apps):
# sudo pacman -S --noconfirm --needed gnome-shell gnome-control-center gnome-terminal nautilus gdm


# ========================================
# HYPRLAND - WM Wayland ultra customisable
# ========================================
# Hyprland = tiling window manager moderne pour Wayland
# sudo pacman -S --noconfirm --needed hyprland

# Outils essentiels pour Hyprland
paru -S --noconfirm --needed waybar hyprlauncher hyprlock hyprpaper hyprshot
		

# Outils optionnels recommandés pour Hyprland:
paru -S --noconfirm --needed wlogout wl-clipboard impala pavucontrol pika-backup swaync waypaper
    # swww \          
    # grim slurp \   
    # swayidle \    
    # brightnessctl

echo "✅ GNOME (stable) + Hyprland (custom) installés"
echo "💡 Choisis au login: GNOME ou Hyprland"

