#!/usr/bin/env bash

echo "install Bitwarden Desktop"

# Alternative: Use Flatpak if COPR doesn't work
flatpak install -y flathub com.bitwarden.desktop > /dev/null 2>&1

echo "Done installation success Bitwarden Desktop"

