#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# Launch terminal on workspace 1
exec-once = hyprctl dispatch exec "[workspace 1] $terminal"
exec-once = hypridle
exec-once = wl-clip-persist --clipboard regular
exec-once = clipse -listen
exec-once = swaync
exec-once = waybar
exec-once = swww-daemon
exec-once = waypaper --restore

# Launch Firefox on workspace 2
exec-once = hyprctl dispatch exec "[workspace 2] firefox"
