# Improve colors
set -g default-terminal 'tmux-256color'
set -s escape-time 0
set  -g base-index 1
set -g history-limit 50000
set -g mouse on

# ============================================================================
# KEYBINDINGS - TMUX SESSIONIZER & FZF
# ============================================================================
bind-key f run-shell "tmux neww ~/.local/scripts/tmux-sessionizer"
bind-key s run-shell "tmux neww ~/.local/scripts/tmux-session-switcher"
bind-key X run-shell "~/.local/scripts/tmux-kill-session"

# vi key mov for copy/paste mode
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

bind c new-window -c "#{pane_current_path}"
bind r source-file ~/.tmux.conf  \; display-message "tmux.conf reloaded"

# Tmux Plugin Manager
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'niksingh710/minimal-tmux-status'

#THEME
set -g @minimal-tmux-use-arrow true
set -g @minimal-tmux-right-arrow ""
set -g @minimal-tmux-left-arrow ""

# These are the default values used inside the plugin to achieve the preview shown above.

set -g @minimal-tmux-fg "#000000"
set -g @minimal-tmux-bg "#698DDA"
set -g @minimal-tmux-justify "centre"
set -g @minimal-tmux-indicator-str "  tmux  "
set -g @minimal-tmux-indicator true
set -g @minimal-tmux-status "top"

# Enables or disables the left and right status bar
set -g @minimal-tmux-right false
set -g @minimal-tmux-left false

# expanded icon (fullscreen icon)
set -g @minimal-tmux-expanded-icon "󰊓 "

# on all tabs (default is false)
# false will make it visible for the current tab only
set -g @minimal-tmux-show-expanded-icons-for-all-tabs true

# To add or remove extra text in status bar
set -g @minimal-tmux-status-right-extra ""
set -g @minimal-tmux-status-left-extra ""


# Not recommended to change these values
set -g @minimal-tmux-status-right "#S"
set -g @minimal-tmux-status-left "refer to code"


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
